# Generated by Django 5.2.17 on 2026-09-08 01:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(help_text='e.g. Software Engineer Intern', max_length=120)),
                ('target_company', models.CharField(blank=True, max_length=120)),
                ('experience_level', models.CharField(choices=[('STU', 'Current student'), ('NEW', 'New graduate'), ('EARLY', 'Early career (1-3 yrs)')], default='STU', max_length=5)),
                ('resume_summary', models.TextField(blank=True, help_text='Plain-text resume the parser turns into an initial skill list.')),
                ('target_interview_date', models.DateField(blank=True, help_text='Deadline Beacon plans backwards from. Blank = open-ended prep.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='One login = one career profile.', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PreparationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. 4-week SWE intern sprint', max_length=150)),
                ('focus_role', models.CharField(max_length=120)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('target_date', models.DateField(help_text='Date the plan must be finished by.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DONE', 'Completed'), ('ARCH', 'Archived')], default='DRAFT', max_length=6)),
                ('generated_by_ai', models.BooleanField(default=True, help_text='False when a user hand-writes or heavily edits the plan.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='preparation.candidateprofile')),
            ],
            options={
                'ordering': ['target_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TECH', 'Technical'), ('BEHAV', 'Behavioral'), ('DOMAIN', 'Domain knowledge'), ('COMM', 'Communication')], default='TECH', max_length=6)),
                ('description', models.TextField(blank=True, help_text='What mastery of this skill looks like in an interview.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='uniq_skill_name_per_category')],
            },
        ),
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)])),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('DOING', 'In progress'), ('DONE', 'Done'), ('SKIP', 'Skipped')], default='TODO', max_length=5)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='preparation.preparationplan')),
                ('skill', models.ForeignKey(blank=True, help_text='Skill gap this task is meant to close.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='preparation.skill')),
            ],
            options={
                'ordering': ['-priority', 'due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_score', models.PositiveSmallIntegerField(help_text='Quiz result, 0-100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('required_level', models.PositiveSmallIntegerField(default=70, help_text='Level the target role demands, 0-100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assessed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='preparation.candidateprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='preparation.skill')),
            ],
            options={
                'ordering': ['-assessed_on', 'skill__name'],
            },
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='candidates', through='preparation.SkillAssessment', to='preparation.skill'),
        ),
        migrations.AddConstraint(
            model_name='preparationplan',
            constraint=models.UniqueConstraint(fields=('candidate', 'title'), name='uniq_plan_title_per_candidate'),
        ),
        migrations.AddConstraint(
            model_name='preparationplan',
            constraint=models.CheckConstraint(condition=models.Q(('target_date__gte', models.F('start_date'))), name='plan_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='plantask',
            constraint=models.UniqueConstraint(fields=('plan', 'title'), name='uniq_task_title_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='skillassessment',
            constraint=models.UniqueConstraint(fields=('candidate', 'skill'), name='uniq_assessment_per_candidate_skill'),
        ),
        migrations.AddConstraint(
            model_name='skillassessment',
            constraint=models.CheckConstraint(condition=models.Q(('proficiency_score__lte', 100), ('required_level__lte', 100)), name='scores_within_0_100'),
        ),
    ]
