# Generated by Django 5.2.17 on 2026-09-08 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantask',
            options={'ordering': ['week_number', '-priority', 'due_date', 'title']},
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preparation_timeline_weeks',
            field=models.PositiveSmallIntegerField(default=6, help_text='Weeks the user says they have. Drives the length of the roadmap.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='primary_concern',
            field=models.CharField(blank=True, choices=[('TECH', 'Technical rounds'), ('BEHAV', 'Behavioral questions'), ('RESUME', 'Resume and elevator pitch'), ('CONF', 'Confidence under pressure'), ('TIME', 'Not enough time to prepare')], help_text='Optional. Used to weight which skill gaps get tackled first.', max_length=6),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Original upload from the drag-and-drop area on the setup screen.', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='rationale',
            field=models.TextField(blank=True, help_text="Why Beacon picked this task - shown under 'Why these recommendations?' and on the recommended-next card."),
        ),
        migrations.AddField(
            model_name='plantask',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Which week of the roadmap this task belongs to (Screen 3).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
    ]
